numb=int(input())
if numb==1:print("I")
elif numb==2:print("II")
elif numb==3:print("III")
elif numb==4:print("IV")
elif numb==5:print("V")
elif numb==6:print("VI")
elif numb==7:print("VII")
elif numb==8:print("VIII")
elif numb==9:print("IX")
elif numb==10:print("X")
else:print("ошибка")