# a=int(input())
# if a>(-1) and a<17: print("Принадлежит")
# else: print("Не принадлежит")
# a=int(input())
# if a>=7 or a<=-3: print("Принадлежит")
# else: print("Не принадлежит")
a=int(input())
if -30<a<=-2 or 7<a<=25:print("Принадлежит")
else:print("Не принадлежит")